# Generated by Django 5.0.3 on 2024-05-04 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_department_administrator_leave_responsibility'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
