# Generated by Django 5.0.3 on 2024-05-21 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrator',
        ),
    ]
