# Generated by Django 5.0.3 on 2024-05-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_administrator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('start_date', models.DateField(verbose_name='Дата начала отпуска')),
                ('end_date', models.DateField(verbose_name='Дата окончания отпуска')),
            ],
        ),
        migrations.RemoveField(
            model_name='responsibility',
            name='position',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='responsible_employee',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Responsibility',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
