# Generated by Django 5.0.3 on 2024-05-22 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_application_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='application',
        ),
    ]
