# Generated by Django 5.0.3 on 2024-05-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_userprofile_application'),  # замените на последнюю миграцию перед добавлением LeaveType
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип отпуска')),
            ],
        ),
    ]
