# Generated by Django 5.0.3 on 2024-05-22 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20240522_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='leave_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main.leavetype'),
            preserve_default=False,
        ),
    ]
